apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-web-deployment
  namespace: testes
  labels:
    app: k8-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8-web
  template:
    metadata:
      labels:
        app: k8-web
    spec:
      containers:
      - name: k8-web
        image: allccodes/k8-web-hello
        ports:
        - containerPort: 3000


---
apiVersion: v1
kind: Service
metadata:
  name: k8-web-service
  namespace: testes
spec:
  selector:
    app: ke8-web
  ports:
  - port: 3000
    nodePort: 30000
  type: NodePort
      
     
    