apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-web-hello-deploy
  namespace: testes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8-web-hello
  template:
    metadata:
      labels:
        app: k8-web-hello
    spec:
      containers:
      - name: k8-web-hello
        image: allccodes/k8-web-hello
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: k8-web-service
  namespace: testes
spec:
  type: LoadBalancer
  selector:
    app: k8-web-hello
  ports:
  - port: 3030
    targetPort: 3000
      
      
