apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
  - name: my-container
    image: nginx
    volumeMounts:
    - name: my-persistent-storage
      mountPath: /data
  volumes:
  - name: my-persistent-storage
    persistentVolumeClaim:
      claimName: my-pvc