apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-web-hello-to-nginx-deploy
  namespace: testes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8-web-hello-to-nginx
  template:
    metadata:
      labels:
        app: k8-web-hello-to-nginx
    spec:
      containers:
      - name: k8-web-hello-nginx
        image: allccodes/k8-web-hello-to-nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: k8-web-hello-to-nginx-service
  namespace: testes
spec:
  type: LoadBalancer
  selector:
    app: k8-web-hello-to-nginx
  ports:
  - port: 3333
    targetPort: 3000
      
      
